name: Deploy .NET Backend

on:
  push:
    branches:
      - BackBranch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy project to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/
            sudo rm -rf notion-backend
            sudo mkdir notion-backend
            cd notion-backend
            sudo git clone --branch BackBranch https://github.com/ImgriffNotion/NotionPV221.git .
            sudo chown $USER:$USER /var/www/notion-backend
            cp -r Backend/* ./
            sudo rm -rf Backend/
            cd NotionBack
            sudo dotnet publish -c Release -o /var/www/notion-backend/publish
            sudo systemctl daemon-reload
            sudo systemctl restart notion-backend
